name: flask pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    outputs:
      imagetag: ${{ steps.tag.outputs.imagetag }}
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 
      with:
        role-to-assume: ${{ secrets.role_arn }}
        role-session-name: oidcsessionName
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      id: tag
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: flask_rest
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "imagetag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  updatemanifest:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout Kubernetes manifest repository
        uses: actions/checkout@v2
        with:
          repository: Abdelali12-codes/flask-app-k8s-manifests-gitops

      - name: Update Kubernetes manifest
        run: |
          echo "sed -i 's@'$ECR_REPO_URI.*'@'$ECR_REPO_URI:$IMAGE_TAG'@'  deployment.yaml"
          sed -i 's@'$ECR_REPO_URI.*'@'$ECR_REPO_URI:$IMAGE_TAG'@'  deployment.yaml
        env:
          ECR_REPO_URI: ${{ needs.deploy.outputs.registry }}:flask_rest
          IMAGE_TAG: ${{ needs.deploy.outputs.imagetag }}

      - name: show files 
        run: |
           ls -l
           git status

      - name: Commit and push changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Update deployment image"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update deployment image
          title: Update deployment image
          body: |
            This PR updates the deployment image to the latest version.
          labels: auto-update
