name: flask pipeline

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      flaskapp: ${{ steps.changes.outputs.flaskapp }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          flaskapp:
            - '**' 
  deploy:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.flaskapp == 'true' }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    outputs:
      imagetag: ${{ steps.tag.outputs.imagetag }}
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 
      with:
        role-to-assume: ${{ secrets.role_arn }}
        role-session-name: oidcsessionName
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      id: tag
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: flask_rest
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "imagetag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  updatemanifest:
    runs-on: ubuntu-latest
    needs: [ deploy, changes ]
    permissions:
      pull-requests: write
      contents: write
    if: ${{ needs.changes.outputs.flaskapp == 'true' }}
    steps:
      - name: Checkout Kubernetes manifest repository
        uses: actions/checkout@v2
        with:
          repository: Abdelali12-codes/flask-app-k8s-manifests-gitops

      - name: Update Kubernetes manifest
        run: |
          echo "sed -i 's@'$ECR_REPO_URI.*'@'$ECR_REPO_URI:$IMAGE_TAG'@'  deployment.yaml"
          sed -i 's@'$ECR_REPO_URI.*'@'$ECR_REPO_URI:$IMAGE_TAG'@'  deployment.yaml
        env:
          ECR_REPO_URI: ${{ needs.deploy.outputs.registry }}/flask_rest
          IMAGE_TAG: ${{ needs.deploy.outputs.imagetag }}

      - name: Commit and push changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Update deployment image"
      - name: Branch name 
        id: br
        run: |
          branch="${needs.deploy.outputs.imagetag: -8}"
          echo "branch=$branch" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          git-token: ${{ secerts.git_token }}
          commit-message: Update deployment image
          branch: ${{ steps.br.outputs.branch }}
          title: Update deployment image
          body: |
            This PR updates the deployment image to the latest version.
          labels: auto-update
